NOTE: This module uses Apptainer (Singularity). Some commands execute inside
the container (e.g. python3, pip3).

NOTE: This module uses Apptainer (Singularity). Some commands execute inside
the container (e.g. python3, pip3).
NOTE: This module uses Apptainer (Singularity). Some commands execute inside
the container (e.g. python3, pip3).

NOTE: This module uses Apptainer (Singularity). Some commands execute inside
the container (e.g. python3, pip3).


NOTE: This module uses Apptainer (Singularity). Some commands execute inside
the container (e.g. python3, pip3).

NOTE: This module uses Apptainer (Singularity). Some commands execute inside
the container (e.g. python3, pip3).

Unused kwargs: ['bnb_8bit_quant_type', 'bnb_8bit_compute_dtype']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Unused kwargs: ['bnb_8bit_quant_type', 'bnb_8bit_compute_dtype']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Unused kwargs: ['bnb_8bit_quant_type', 'bnb_8bit_compute_dtype']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Unused kwargs: ['bnb_8bit_quant_type', 'bnb_8bit_compute_dtype']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Unused kwargs: ['bnb_8bit_quant_type', 'bnb_8bit_compute_dtype']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Unused kwargs: ['bnb_8bit_quant_type', 'bnb_8bit_compute_dtype']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1403, in hf_hub_download
    raise head_call_error
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1674, in get_hf_file_metadata
    r = _request_wrapper(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 369, in _request_wrapper
    response = _request_wrapper(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 393, in _request_wrapper
    hf_raise_for_status(response)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 321, in hf_raise_for_status
    raise GatedRepoError(message, response) from e
huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-66437561-4ba8a2d77186272a15e6b461;a49f869f-d480-43b2-ade2-321f64d879ed)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-70B-Instruct is restricted. You must be authenticated to access it.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 415, in <module>
    main()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 406, in main
    optimizer = Optimizer()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 290, in __init__
    self.model, self.tokenizer = load_model(args.model, cache_dir, quantization=args.quantization)
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 95, in load_model
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, device_map="auto", quantization_config=quantization_config, cache_dir=cache_dir)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    config, kwargs = AutoConfig.from_pretrained(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
    response.raise_for_status()
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1403, in hf_hub_download
    raise head_call_error
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1674, in get_hf_file_metadata
    r = _request_wrapper(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 369, in _request_wrapper
    response = _request_wrapper(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 393, in _request_wrapper
    hf_raise_for_status(response)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 321, in hf_raise_for_status
    raise GatedRepoError(message, response) from e
huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-66437561-58962cb10dea649313d4b317;638111e9-7501-455f-b1ab-e0aa8075f48d)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted. You must be authenticated to access it.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 415, in <module>
    main()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 406, in main
    optimizer = Optimizer()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 290, in __init__
    self.model, self.tokenizer = load_model(args.model, cache_dir, quantization=args.quantization)
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 95, in load_model
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, device_map="auto", quantization_config=quantization_config, cache_dir=cache_dir)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 416, in cached_file
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    raise EnvironmentError(
    resolved_config_file = cached_file(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct.
401 Client Error. (Request ID: Root=1-66437561-4ba8a2d77186272a15e6b461;a49f869f-d480-43b2-ade2-321f64d879ed)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-70B-Instruct is restricted. You must be authenticated to access it.  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 416, in cached_file

    raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct.
401 Client Error. (Request ID: Root=1-66437561-58962cb10dea649313d4b317;638111e9-7501-455f-b1ab-e0aa8075f48d)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted. You must be authenticated to access it.
Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1403, in hf_hub_download
    raise head_call_error
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 1674, in get_hf_file_metadata
    r = _request_wrapper(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 369, in _request_wrapper
    response = _request_wrapper(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/file_download.py", line 393, in _request_wrapper
    hf_raise_for_status(response)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 321, in hf_raise_for_status
    raise GatedRepoError(message, response) from e
huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-66437561-3dad32fd64b2d0f82ef8ce5a;b1d1ed89-3a02-4e27-886d-6adaea141708)

Cannot access gated repo for url https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1/resolve/main/config.json.
Access to model mistralai/Mixtral-8x22B-Instruct-v0.1 is restricted. You must be authenticated to access it.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 415, in <module>
    main()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 406, in main
    optimizer = Optimizer()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 290, in __init__
    self.model, self.tokenizer = load_model(args.model, cache_dir, quantization=args.quantization)
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 95, in load_model
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, device_map="auto", quantization_config=quantization_config, cache_dir=cache_dir)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/utils/hub.py", line 416, in cached_file
    raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1.
401 Client Error. (Request ID: Root=1-66437561-3dad32fd64b2d0f82ef8ce5a;b1d1ed89-3a02-4e27-886d-6adaea141708)

Cannot access gated repo for url https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1/resolve/main/config.json.
Access to model mistralai/Mixtral-8x22B-Instruct-v0.1 is restricted. You must be authenticated to access it.
Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 415, in <module>
    main()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 406, in main
    optimizer = Optimizer()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 290, in __init__
    self.model, self.tokenizer = load_model(args.model, cache_dir, quantization=args.quantization)
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 95, in load_model
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, device_map="auto", quantization_config=quantization_config, cache_dir=cache_dir)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/modeling_utils.py", line 3627, in from_pretrained
    hf_quantizer.validate_environment(device_map=device_map)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/quantizers/quantizer_bnb_8bit.py", line 86, in validate_environment
    raise ValueError(
ValueError: 
                    Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the
                    quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules
                    in 32-bit, you need to set `llm_int8_enable_fp32_cpu_offload=True` and pass a custom `device_map` to
                    `from_pretrained`. Check
                    https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                    for more details.
                    
Loading checkpoint shards:  25%|██▌       | 1/4 [00:12<00:38, 12.72s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:27<00:27, 13.88s/it]Downloading shards:  25%|██▌       | 1/4 [00:35<01:46, 35.50s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:46<00:16, 16.29s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:01<00:00, 15.60s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:01<00:00, 15.28s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[I 2024-05-14 17:31:05,793] A new study created in memory with name: no-name-d96ece42-7b21-4812-a51f-e18d6ddc9848
/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/generation/configuration_utils.py:497: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/generation/configuration_utils.py:509: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(
Downloading shards:  50%|█████     | 2/4 [01:14<01:15, 37.69s/it]Unused kwargs: ['bnb_8bit_quant_type', 'bnb_8bit_compute_dtype']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Downloading shards:   0%|          | 0/62 [00:00<?, ?it/s]Downloading shards:  75%|███████▌  | 3/4 [01:49<00:36, 36.49s/it]Downloading shards: 100%|██████████| 4/4 [02:10<00:00, 30.33s/it]Downloading shards: 100%|██████████| 4/4 [02:10<00:00, 32.67s/it]
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:17<00:52, 17.51s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:32<00:31, 15.99s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:53<00:18, 18.36s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:05<00:00, 15.89s/it]Loading checkpoint shards: 100%|██████████| 4/4 [01:05<00:00, 16.43s/it]
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 415, in <module>
    main()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 406, in main
    optimizer = Optimizer()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 290, in __init__
    self.model, self.tokenizer = load_model(args.model, cache_dir, quantization=args.quantization)
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 102, in load_model
    tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, padding_side="left")
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 862, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2311, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 124, in __init__
    super().__init__(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 102, in __init__
    raise ValueError(
ValueError: Cannot instantiate this tokenizer from a slow version. If it's based on sentencepiece, make sure you have sentencepiece installed.
Downloading shards:   2%|▏         | 1/62 [05:17<5:22:42, 317.43s/it]Downloading shards:   3%|▎         | 2/62 [06:19<2:47:15, 167.27s/it]Downloading shards:   5%|▍         | 3/62 [06:49<1:42:46, 104.51s/it]Downloading shards:   6%|▋         | 4/62 [10:02<2:14:48, 139.45s/it]Downloading shards:   8%|▊         | 5/62 [17:23<3:55:51, 248.27s/it]Downloading shards:  10%|▉         | 6/62 [32:26<7:19:20, 470.72s/it]Downloading shards:  11%|█▏        | 7/62 [33:43<5:13:37, 342.14s/it]Downloading shards:  13%|█▎        | 8/62 [34:56<3:50:46, 256.42s/it]Downloading shards:  15%|█▍        | 9/62 [38:44<3:38:42, 247.60s/it]Downloading shards:  16%|█▌        | 10/62 [40:04<2:49:47, 195.91s/it]Downloading shards:  18%|█▊        | 11/62 [42:31<2:33:47, 180.93s/it]Downloading shards:  19%|█▉        | 12/62 [43:42<2:02:55, 147.52s/it]Downloading shards:  21%|██        | 13/62 [44:45<1:39:25, 121.74s/it]Downloading shards:  23%|██▎       | 14/62 [45:47<1:23:05, 103.87s/it]Downloading shards:  24%|██▍       | 15/62 [46:57<1:13:11, 93.43s/it] Downloading shards:  26%|██▌       | 16/62 [49:11<1:21:08, 105.85s/it]Downloading shards:  27%|██▋       | 17/62 [50:14<1:09:37, 92.84s/it] Downloading shards:  29%|██▉       | 18/62 [51:46<1:07:56, 92.65s/it]Downloading shards:  31%|███       | 19/62 [53:37<1:10:16, 98.06s/it]Downloading shards:  32%|███▏      | 20/62 [1:00:41<2:17:11, 196.00s/it]Downloading shards:  34%|███▍      | 21/62 [1:02:47<1:59:39, 175.11s/it]Downloading shards:  35%|███▌      | 22/62 [1:09:20<2:40:19, 240.49s/it]Downloading shards:  37%|███▋      | 23/62 [1:11:12<2:11:15, 201.93s/it]Downloading shards:  39%|███▊      | 24/62 [1:13:18<1:53:20, 178.95s/it]Downloading shards:  40%|████      | 25/62 [1:14:45<1:33:19, 151.33s/it]Downloading shards:  42%|████▏     | 26/62 [1:15:53<1:15:52, 126.45s/it]Downloading shards:  44%|████▎     | 27/62 [1:17:15<1:06:02, 113.21s/it]Downloading shards:  45%|████▌     | 28/62 [1:18:55<1:01:50, 109.13s/it]Downloading shards:  47%|████▋     | 29/62 [1:20:17<55:29, 100.89s/it]  [W 2024-05-14 18:59:24,640] Trial 0 failed with parameters: {'window_size': 423, 'do_sample': False} because of the following error: FileNotFoundError(2, 'No such file or directory').
Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 393, in objective
    with open(args.output_file, "at", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'gridout_8bit_Qwen/Qwen1.5-7B-Chat.jsonl'
[W 2024-05-14 18:59:24,685] Trial 0 failed with value None.
Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 415, in <module>
    main()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 408, in main
    study.optimize(optimizer.objective, n_trials=args.ntrials)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/optuna/study/_optimize.py", line 62, in _optimize
    _optimize_sequential(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/optuna/study/_optimize.py", line 159, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/optuna/study/_optimize.py", line 247, in _run_trial
    raise func_err
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 393, in objective
    with open(args.output_file, "at", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'gridout_8bit_Qwen/Qwen1.5-7B-Chat.jsonl'
Downloading shards:  48%|████▊     | 30/62 [1:35:32<3:04:05, 345.16s/it]Downloading shards:  50%|█████     | 31/62 [1:36:47<2:16:27, 264.10s/it]Downloading shards:  52%|█████▏    | 32/62 [1:38:33<1:48:20, 216.69s/it]Downloading shards:  53%|█████▎    | 33/62 [1:42:10<1:44:49, 216.89s/it]Downloading shards:  55%|█████▍    | 34/62 [1:43:13<1:19:36, 170.58s/it]Downloading shards:  56%|█████▋    | 35/62 [1:52:40<2:10:18, 289.59s/it]Downloading shards:  58%|█████▊    | 36/62 [2:02:40<2:45:53, 382.82s/it]Downloading shards:  60%|█████▉    | 37/62 [2:09:29<2:42:47, 390.71s/it]Downloading shards:  61%|██████▏   | 38/62 [2:10:32<1:56:52, 292.19s/it]Downloading shards:  63%|██████▎   | 39/62 [2:11:40<1:26:16, 225.05s/it]Downloading shards:  65%|██████▍   | 40/62 [2:12:45<1:04:57, 177.15s/it]Downloading shards:  66%|██████▌   | 41/62 [2:13:48<49:59, 142.81s/it]  Downloading shards:  68%|██████▊   | 42/62 [2:15:34<43:55, 131.76s/it]Downloading shards:  69%|██████▉   | 43/62 [2:22:11<1:06:56, 211.38s/it]Downloading shards:  71%|███████   | 44/62 [2:23:14<50:04, 166.89s/it]  Downloading shards:  73%|███████▎  | 45/62 [2:25:07<42:42, 150.72s/it]Downloading shards:  74%|███████▍  | 46/62 [2:26:10<33:09, 124.32s/it]Downloading shards:  76%|███████▌  | 47/62 [2:33:54<56:34, 226.29s/it]Downloading shards:  77%|███████▋  | 48/62 [2:51:09<1:49:24, 468.89s/it]Downloading shards:  79%|███████▉  | 49/62 [2:55:54<1:29:38, 413.70s/it]Downloading shards:  81%|████████  | 50/62 [2:58:12<1:06:12, 331.03s/it]Downloading shards:  82%|████████▏ | 51/62 [2:59:20<46:10, 251.87s/it]  Downloading shards:  84%|████████▍ | 52/62 [3:00:22<32:31, 195.17s/it]Downloading shards:  85%|████████▌ | 53/62 [3:03:34<29:07, 194.13s/it]Downloading shards:  87%|████████▋ | 54/62 [3:05:31<22:47, 170.95s/it]Downloading shards:  89%|████████▊ | 55/62 [3:06:34<16:09, 138.49s/it]Downloading shards:  90%|█████████ | 56/62 [3:20:25<34:38, 346.42s/it]Downloading shards:  92%|█████████▏| 57/62 [3:21:42<22:06, 265.40s/it]Downloading shards:  94%|█████████▎| 58/62 [3:22:44<13:37, 204.45s/it]Downloading shards:  95%|█████████▌| 59/62 [3:23:47<08:06, 162.05s/it]Downloading shards:  97%|█████████▋| 60/62 [3:28:50<06:48, 204.32s/it]Downloading shards:  98%|█████████▊| 61/62 [3:30:52<02:59, 179.58s/it]Downloading shards: 100%|██████████| 62/62 [3:31:36<00:00, 139.07s/it]Downloading shards: 100%|██████████| 62/62 [3:31:36<00:00, 204.79s/it]
/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/accelerate/utils/modeling.py:1363: UserWarning: Current model requires 528486336 bytes of buffer for offloaded layers, which seems does not fit any GPU's remaining memory. If you are experiencing a OOM later, please consider using offload_buffers=True.
  warnings.warn(
Traceback (most recent call last):
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 415, in <module>
    main()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 406, in main
    optimizer = Optimizer()
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 290, in __init__
    self.model, self.tokenizer = load_model(args.model, cache_dir, quantization=args.quantization)
  File "/scratch/project_2005072/cassandra/ocr-postcorrection-lm/scripts/../gridsearch.py", line 95, in load_model
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, device_map="auto", quantization_config=quantization_config, cache_dir=cache_dir)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/modeling_utils.py", line 3627, in from_pretrained
    hf_quantizer.validate_environment(device_map=device_map)
  File "/scratch/project_2005072/cassandra/.venv/lib64/python3.9/site-packages/transformers/quantizers/quantizer_bnb_8bit.py", line 86, in validate_environment
    raise ValueError(
ValueError: 
                    Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the
                    quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules
                    in 32-bit, you need to set `llm_int8_enable_fp32_cpu_offload=True` and pass a custom `device_map` to
                    `from_pretrained`. Check
                    https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                    for more details.
                    
